#端口号配置
server:
  port: 8766
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project02?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      #验证连接的有效性
      test-while-idle: true
      #在连接归还到连接池时是否测试该连接
      test-on-borrow: false
      validation-query: SELECT 1 FROM DUAL
      #空闲连接回收的时间间隔，与test-while-idle一起使用
      time-between-eviction-runs-millis: 60000
      #连接池空闲连接的有效时间 ，设置30秒
      min-evictable-idle-time-millis: 300000
      # 初始连接数
      initial-size: 100
      #指定连接池中最大的活跃连接数.
      max-active: 400
      #指定连接池等待连接返回的最大等待时间，毫秒单位.
      max-wait: 10000
      #指定必须保持连接的最小值
      min-idle: 100
mybatis:
  mapper-locations:
  - classpath*:sqlmap/*Mapper.xml
  type-aliases-package: org.springboot.sample.entity
AppId: wxb6bbbfbe7352fb5c
AppSecret: bfa18426504397bae635516bec0f7929
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level.root: info
#  level.com.zimuka: debug
#  path: logs/
#  file: zimuka-peers.log