server:
  port: 8766  #端口号配置
spring:
  datasource:
    url: jdbc:mysql://bj-cdb-7j9kfsay.sql.tencentcdb.com:63067/gzwh_findPeer?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: gzwh2018
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true #验证连接的有效性
      test-on-borrow: false #在连接归还到连接池时是否测试该连接
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 60000  #空闲连接回收的时间间隔，与test-while-idle一起使用
      min-evictable-idle-time-millis: 300000  #连接池空闲连接的有效时间 ，设置30秒
      initial-size: 100 # 初始连接数
      max-active: 400 #指定连接池中最大的活跃连接数.
      max-wait: 10000 #指定连接池等待连接返回的最大等待时间，毫秒单位.
      min-idle: 100 #指定必须保持连接的最小值
  redis:
    database: 0 #数据库名称，默认为db0
    host: localhost #服务器地址
    password: #数据库密码
    port: 6379  #连接端口号
mybatis:
  mapper-locations:
  - classpath*:sqlmap/*Mapper.xml
  type-aliases-package: org.springboot.sample.entity
AppId: wx34fefa15f676d944
AppSecret: f4ce303b50267dc17dc69ae083ae3a98
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level.root: info
#  level.com.zimuka: debug
#  path: logs/
#  file: zimuka-peers.log